services:
  web:
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_SITE_URL: http://localhost:3000

  worker:
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
